### ISSUE TITLE
symfony/yaml version

### ISSUE THREAD

**Issue by bryanrscott** [laravel-doctrine/migrations#10]
Hi

Just doing a default install, along the lines below and when adding migrations get a package conflict on symfony/yaml[v2.3.0, v3.0.0]. I suspect that v3 has been released recently

To reproduce
composer create-project laravel/laravel --prefer-dist app_name
cd app_name
composer require firebase/php-jwt
composer require guzzlehttp/guzzle
composer require laravel-doctrine/orm
composer require laravel-doctrine/extensions
composer require laravel-doctrine/acl
composer require laravel-doctrine/migrations

**Comment by patrickbrouwers** [comment]
Does composer error out of just show a warning?

Anyway it's a issue with the parent package (https://github.com/doctrine/migrations/blob/v1.1.0/composer.json#L15), not a lot we can do about it. Best you open an issue over there.

**Comment by bryanrscott** [comment]
Hi

The full list

Using version ^1.0 for laravel-doctrine/migrations
./composer.json has been updated

> php artisan clear-compiled
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - laravel-doctrine/migrations 1.0.0 requires laravel-doctrine/orm dev-master -> no matching package found.
    - laravel-doctrine/migrations 1.0.2 requires doctrine/migrations ~1.1.0 -> satisfiable by doctrine/migrations[v1.1.0].
    - laravel-doctrine/migrations 1.0.3 requires doctrine/migrations ~1.1.0 -> satisfiable by doctrine/migrations[v1.1.0].
    - Conclusion: don't install doctrine/migrations v1.1.0
    - laravel-doctrine/migrations 1.0.1 requires doctrine/migrations ~1.0.0 -> satisfiable by doctrine/migrations[v1.0.0].
    - Conclusion: remove symfony/yaml v3.0.0
    - Installation request for laravel-doctrine/migrations ^1.0 -> satisfiable by laravel-doctrine/migrations[1.0.0, 1.0.1, 1.0.2, 1.0.3].
    - Conclusion: don't install symfony/yaml v3.0.0
    - doctrine/migrations v1.0.0 requires symfony/yaml ~2.3 -> satisfiable by symfony/yaml[v2.3.0, v2.3.1, v2.3.10, v2.3.11, v2.3.12, v2.3.13, v2.3.14, v2.3.15, v2.3.16, v2.3.17, v2.3.18, v2.3.19, v2.3.2, v2.3.20, v2.3.21, v2.3.22, v2.3.23, v2.3.24, v2.3.25, v2.3.26, v2.3.27, v2.3.28, v2.3.29, v2.3.3, v2.3.30, v2.3.31, v2.3.32, v2.3.33, v2.3.34, v2.3.35, v2.3.4, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9, v2.4.0, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.8.0].
    - Can only install one of: symfony/yaml[v2.3.0, v3.0.0].  
    .....snipped
    - Can only install one of: symfony/yaml[v2.8.0, v3.0.0].
    - Installation request for symfony/yaml == 3.0.0.0 -> satisfiable by symfony/yaml[v3.0.0].

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

Read https://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

Installation failed, reverting ./composer.json to its original content.

**Comment by mikeSimonson** [comment]
@bryanrscott Can you show your composer.json ? thanks

**Comment by bryanrscott** [comment]
sure I am actually testing installing from scratch from laravel

{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.1._",
        "illuminate/html": "^5.0",
        "firebase/php-jwt": "^3.0",
        "guzzlehttp/guzzle": "^6.1",
        "laravel-doctrine/orm": "^1.0",
        "laravel-doctrine/extensions": "^1.0",
        "laravel-doctrine/acl": "^1.0",
        "laravel/socialite": "^2.0",
        "maatwebsite/excel": "^2.0",
        "gedmo/doctrine-extensions": "^2.4"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9._",
        "phpunit/phpunit": "~4.0",
        "phpspec/phpspec": "~2.1"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\": "app/"
        }
    },
    "autoload-dev": {
        "classmap": [
            "tests/TestCase.php"
        ]
    },
    "scripts": {
        "post-install-cmd": [
            "php artisan clear-compiled",
            "php artisan optimize"
        ],
        "pre-update-cmd": [
            "php artisan clear-compiled"
        ],
        "post-update-cmd": [
            "php artisan optimize"
        ],
        "post-root-package-install": [
            "php -r \"copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ]
    },
    "config": {
        "preferred-install": "dist"
    }
}

On 7 December 2015 at 19:35, mikeSimonson notifications@github.com wrote:

> @bryanrscott https://github.com/bryanrscott Can you show your
> composer.json ? thanks
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/laravel-doctrine/migrations/issues/10#issuecomment-162448135
> .

## 

Bryan Scott
Database Administrator
Pacific Island Forum Fisheries Agency
http://www.ffa.int

**Comment by mikeSimonson** [comment]
@bryanrscott I need to fix master and tag a new release to fix that. It will be done this week.

**Comment by bryanrscott** [comment]
Great.  thanks

**Comment by joshhornby** [comment]
@mikeSimonson Any update on this?

**Comment by bryanrscott** [comment]
Hi

Looks like the doctrine/migrations has been updated.  Thanks.  Updated version is 1.2.

Now failing as  
Problem 1
    - laravel-doctrine/migrations 1.0.4 requires doctrine/migrations ~1.1.0 -> no matching package found

Just wondering if laravel-doctrine/migrations dependancy could be updated to support doctrine/migrations@1.2

**Comment by patrickbrouwers** [comment]
Yes, if you can make a PR for that, would be great :)

**Comment by patrickbrouwers** [comment]
Tagged as 1.0.5
