### ISSUE TITLE
Add support for Laravel 8

### ISSUE THREAD

**Issue by martio** [laravel-doctrine/migrations#100]
Hi! Please support for Laravel ver. 8.x 👍

**Comment by eigan** [comment]
2.2.0 released thanks to @sojeda in #101, please try it out! :)

**Comment by froccsos** [comment]
Hi @eigan! 

You should check this: https://packagist.org/packages/laravel-doctrine/migrations#2.2.0 
```
requires

php: ^7.2
doctrine/migrations: ~2.2
illuminate/config: ^7.0
illuminate/console: ^7.0
illuminate/contracts: ^7.0
laravel-doctrine/orm: ^1.6
```

**Comment by eigan** [comment]
Sorry for this. I actually did the same mistake in https://github.com/laravel-doctrine/extensions/issues/50.. :man_facepalming: 

Thanks for letting me know! I should test better myself.

**Comment by froccsos** [comment]
Thank you! :)
