### ISSUE TITLE
Option organize_migrations not working when generating migrations

### ISSUE THREAD

**Issue by downace** [laravel-doctrine/migrations#103]
`laravel-doctrine/migrations=2.2.0`
`laravel-doctrine/orm=1.7.1`

`doctrine:migrations:generate` and `doctrine:migrations:diff` commands.

`\LaravelDoctrine\Migrations\Output\MigrationFileGenerator::generate` uses `\Doctrine\Migrations\Configuration\Configuration::getMigrationsDirectory` which just returns migrations directory and ignores organization options.

If I got it right, `\Doctrine\Migrations\Tools\Console\Helper\MigrationDirectoryHelper` may be used in `\LaravelDoctrine\Migrations\Output\MigrationFileGenerator::generate` to obtain directory for new migration. As in `\Doctrine\Migrations\Generator\Generator::generateMigration`

**Comment by eigan** [comment]
Likely resolved in 3.x because everything is now handled by doctrine/migrations itself.
