### ISSUE TITLE
issue installing package in laravel 9

### ISSUE THREAD

**Issue by Felipe-Castillo** [laravel-doctrine/migrations#119]
I am trying to install the migrations on a fresh install of laravel 9, however I am getting this error
` Problem 1
    - Root composer.json requires laravel-doctrine/migrations ^2.3 -> satisfiable by laravel-doctrine/migrations[2.3.0, 2.3.1, 2.x-dev].
    - laravel-doctrine/migrations[2.3.0, ..., 2.x-dev] require illuminate/config ^6.0|^7.0|^8.0 -> found illuminate/config[v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.

You can also try re-running composer require with an explicit version constraint, e.g. "composer require laravel-doctrine/migrations:*" to figure out if any version is installable, or "composer require laravel-doctrine/migrations:^2.1" if you know which you need.`

previously I installed the orm with this command

`composer require laravel-doctrine/orm`

I have tried to install other versions but the message is the same

composer.json

`{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "require": {
        "php": "^8.0.2",
        "guzzlehttp/guzzle": "^7.2",
        "laravel-doctrine/orm": "^1.8",
        "laravel-doctrine/migrations":"^2.3",
        "laravel/framework": "^9.19",
        "laravel/sanctum": "^3.0",
        "laravel/tinker": "^2.7"
    },
    "require-dev": {
        "fakerphp/faker": "^1.9.1",
        "laravel/pint": "^1.0",
        "laravel/sail": "^1.0.1",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^6.1",
        "phpunit/phpunit": "^9.5.10",
        "spatie/laravel-ignition": "^1.0"
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-update-cmd": [
            "@php artisan vendor:publish --tag=laravel-assets --ansi --force"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true,
        "allow-plugins": {
            "pestphp/pest-plugin": true
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
`

**Comment by eigan** [comment]
There is no other output? 

Have you tried any of the other suggestions provided by composer in the output you posted?

Make sure you have doctrine/cache 1.*

**Comment by JamieGraizevsky** [comment]
I am also having the same issue with a fresh install of laravel 9, created the project then run

`composer require laravel-doctrine/orm` this was successful, but when trying to install migrations `composer require laravel-doctrine/migrations ` I then get this ...

<img width="1993" alt="Screenshot 2022-11-30 at 10 15 20" src="https://user-images.githubusercontent.com/89082138/204769586-809efc0e-4200-4f19-8dc8-488479e733ee.png">

No matter how much i play with the versions of other packages i always get this issue

**Comment by Felipe-Castillo** [comment]
> I am also having the same issue with a fresh install of laravel 9, created the project then run
> 
> `composer require laravel-doctrine/orm` this was successful, but when trying to install migrations `composer require laravel-doctrine/migrations ` I then get this ...
> 
> <img alt="Screenshot 2022-11-30 at 10 15 20" width="1993" src="https://user-images.githubusercontent.com/89082138/204769586-809efc0e-4200-4f19-8dc8-488479e733ee.png">
> 
> No matter how much i play with the versions of other packages i always get this issue

Hi laravel-doctrine isn't working well with laravel 9 for now, I fixed it using laravel 8, check this post 
https://stackoverflow.com/questions/74539303/issue-installing-laravel-doctrine-migrations-package-in-laravel-9

**Comment by eigan** [comment]
https://github.com/laravel-doctrine/migrations/issues/117
