### ISSUE TITLE
[3.x] command doctrine:migrations:rollback defines version argument which is ignored

### ISSUE THREAD

**Issue by whizzrd** [laravel-doctrine/migrations#123]
The `doctrine:migrations:rollback` command defines an optional `version` argument 

https://github.com/laravel-doctrine/migrations/blob/b0966374118be51a31696857f37d902b7d3f3350/src/Console/RollbackCommand.php#L15

which is ignored, it always seems to invoke `doctrine:migrations:migrate version=prev`

https://github.com/laravel-doctrine/migrations/blob/b0966374118be51a31696857f37d902b7d3f3350/src/Console/RollbackCommand.php#L31

```
php artisan doctrine:migrations:rollback --help
Description:
  Rollback to the previous migration

Usage:
  doctrine:migrations:rollback [options] [--] [<version>]
```

Before I send a pull request: what is the intended behavior? Is it supposed to accept a version and roll back to it as `doctrine:migrations:migrate <version>` does, or not accept the optional argument?

**Comment by eigan** [comment]
Thanks for the report @whizzrd :)
