### ISSUE TITLE
[3.x] doctrine:migrations:execute command expects array of versions

### ISSUE THREAD

**Issue by whizzrd** [laravel-doctrine/migrations#126]
```
php artisan doctrine:migrations:execute '20230124073309' --down
# ...
 TypeError 

  array_map(): Argument #2 ($array) must be of type array, string given
```

**Comment by eigan** [comment]
Hm, looks like we need to append `?*` to the `versions` argument.

**Comment by eigan** [comment]
Should be fixed by f9e891c94e6433a38b8ad1b76bf133d83663cfa9 I think.

**Comment by whizzrd** [comment]
Thanks @eigan, you beat my PR

**Comment by eigan** [comment]
Removed the questionmark in 53b918272c951e60caa40b6acdc050942041892f, which caused the argument to be optional.
