### ISSUE TITLE
RefreshCommand uses non existing option for ResetCommand

### ISSUE THREAD

**Issue by SPie** [laravel-doctrine/migrations#129]
The `RefreshCommand` doesn't work for me anymore with the new `3.0.0` version.
I get the error `Symfony\Component\Console\Exception\InvalidOptionException: The "--em" option does not exist.`
The `RefreshCommand` now uses an option called `--em` for the `ResetCommand`

https://github.com/laravel-doctrine/migrations/blob/f520bc8fe98d03f03c31e627406b86f7142c6a3a/src/Console/RefreshCommand.php#L28-L30

but the `ResetCommand` doesn't use the option `em`, but `connection`.

https://github.com/laravel-doctrine/migrations/blob/f520bc8fe98d03f03c31e627406b86f7142c6a3a/src/Console/ResetCommand.php#L21-L23

I could open a MR to handle the error.

And also, if it is ok to tackle that in the same MR, I would like to add the `--no-interaction` option, because right now the `RefreshCommand` won't work in tests anymore.

**Comment by eigan** [comment]
Thanks for the report @SPie! Was a simple fix so I just commited and released a new version now.
