### ISSUE TITLE
Support for UUID field type

### ISSUE THREAD

**Issue by ngrevet** [laravel-doctrine/migrations#18]
I'm trying to implement a schema migration involving a custom `uuid` field type but I'm not exactly sure if this is something that can be done using the `LaravelDoctrine\Migrations` classes. I added my custom type to the doctrine configuration and mapping as so:

``` php
'mapping_types' => [
    'uuid'        => 'uuid',
    'uuid_binary' => 'binary',
],
'custom_types' => [
    'uuid'        => Ramsey\Uuid\Doctrine\UuidType::class,
    'uuid_binary' => Ramsey\Uuid\Doctrine\UuidBinaryType::class,
]
```

But it doesn't seem like the query/schema builder supports custom types at all:

```
$table->uuid('id');

  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Fatal error: Call to undefined method LaravelDoctrine\Migrations\Schema\Table::uuid()
```

 So I went back and just tried to create a `BINARY(16)` to store my UUID by doing this in the migration:

``` php
namespace Database\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema as Schema;
use LaravelDoctrine\Migrations\Schema\Builder;
use LaravelDoctrine\Migrations\Schema\Table;

class Version20160126164625 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $builder = new Builder($schema);
        $builder->create('payment_types', function(Table $table) {
            $table->binary('id', 16);
            $table->string('name');
        });
    }
}
```

But the builder doesn't support `length` on binary fields and doesn't support the [`uuid` field type from Laravel](https://laravel.com/docs/5.2/migrations#creating-columns) either. Do you have any idea how we're supposed to proceed in this situation?

**Comment by josenicomaia** [comment]
@ngrevet-lightspeed Question, why are you using mapping_types? Is there an uuid or uuid_binary database type?

**Comment by ngrevet** [comment]
Yeah, no, I guess I copy-pasted the wrong part. That was part of an earlier testing.

**Comment by josenicomaia** [comment]
@ngrevet-lightspeed I am not using UUID, but what about using and string field for uuid?

**Comment by ngrevet** [comment]
Nope, that's not a possibility, storing it as a string field would reduce performance. We need it to be a `BINARY(16)`. Is there any way to do that except by directly writing the SQL as-is in the migration scripts? How to write migrations for custom doctrine types?

**Comment by josenicomaia** [comment]
I studied the code and come to an conclusion.

For now, you can workarround this with:

``` php
namespace Database\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema as Schema;
use LaravelDoctrine\Migrations\Schema\Builder;
use LaravelDoctrine\Migrations\Schema\Table;

class Version20160126164625 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $builder = new Builder($schema);
        $builder->create('payment_types', function(Table $table) {
            $table->getTable()->addColumn('id', Doctrine\DBAL\Types\Type::BINARY, ['length' => 16])->setNotnull(false);
            $table->string('name');
        });
    }
}
```

After that, I suggest you to PR an improvement to Table::binary ( https://github.com/laravel-doctrine/migrations/blob/1.0/src/Schema/Table.php#L426 ) in order to add lenght to the method.

I hope this help you.

**Comment by josenicomaia** [comment]
Confirmed. It's the length option.

`
length (integer): The maximum length of the column. Only applies to Doctrine’s string and binary types. Defaults to null and is evaluated to 255 in the platform.
`

http://doctrine-orm.readthedocs.org/projects/doctrine-dbal/en/latest/reference/schema-representation.html#portable-options

**Comment by josenicomaia** [comment]
@ngrevet-lightspeed If you test this. I could PR this for you.

**Comment by patrickbrouwers** [comment]
It's possible the builder is not complete.

What about letting doctrine generate the migrations for you? (Diff tool)

**Comment by ngrevet** [comment]
That sounds pretty smart @josenicomaia, I'm on vacations for now, but will test this as soon as I'm back!

**Comment by josenicomaia** [comment]
@ngrevet-lightspeed Diff tool is amazing!! Doctrine generate the migrations automaticaly from your entities changes.

**Comment by ngrevet** [comment]
Thanks @josenicomaia, the `$table->getTable()->addColumn()` with a length worked wonderfully. I can't believe I missed it! This will make things much simpler.

**Comment by josenicomaia** [comment]
@ngrevet-lightspeed Great!
It's a workarround. I will post an PR to solve it properly and you will be able to use `$table->binary('id', 16);` normaly.

I will let you know when the PR were merged to the project.

**Comment by ngrevet** [comment]
Alright, even better! Thanks a lot.
