### ISSUE TITLE
doctrine:schema:update tries to drop the migration table

### ISSUE THREAD

**Issue by driesvints** [laravel-doctrine/migrations#19]
When running `php artisan doctrine:schema:update --sql` I get the following output:

```
$ php artisan doctrine:schema:update --sql
Checking if database needs updating....
Outputting update query:
DROP TABLE doctrine_migration_version;
```

This shouldn't happen as the `doctrine_migration_version` table is the table which stores the migrations (as set in our configuration).

Using `laravel-doctrine/migrations` 1.0.6 & `laravel-doctrine/orm` 1.1.2

**Comment by patrickbrouwers** [comment]
That's strange, will look into it. Don't have the issue myself.

**Comment by driesvints** [comment]
The odd thing is that when I run `php artisan doctrine:migrations:diff` that specific rule doesn't gets written into a new migration file. So I suspect the check for the migration table is specifically missing from the `doctrine:schema:update` command.

**Comment by patrickbrouwers** [comment]
Still not able to reproduce it, I can run `schema:update` without loosing my `migrations` table. 

Assuming you change your config from `migrations` to `doctrine_migration_version`?

**Comment by driesvints** [comment]
Heya, sorry for the late response. I'll try to see today if I can reproduce the problem again. I'll let you know.

**Comment by driesvints** [comment]
Ok, this is pretty embarrassing 😅

Turns out, there was a custom `SchemaUpdateCommand` registered which overwrote the Laravel Doctrine one and was pretty outdated with the newer implementation. That's why some things like the migration table check failed.

I'm very sorry about this. I totally missed this. Sorry for waisting your time! 😓

**Comment by patrickbrouwers** [comment]
No problem :) Glad to hear the package is working as it should :)
