### ISSUE TITLE
Named migrations

### ISSUE THREAD

**Issue by michaelk83** [laravel-doctrine/migrations#20]
I would like to include the purpose of each migration in the file name. So instead of `Version20150915130401.php`, it might be something like `Version20150915130401.cool_new_feature.php`. Then it would be easily visible what each migration does.

I saw in the code that there's a `NamingStrategy` interface and an undocumented `naming_strategy` config setting, which I can use to implement a custom naming strategy. But it would be nice to have console command support for working with named migrations.

**Comment by patrickbrouwers** [comment]
Have tried that once, didn't get it to work properly. Doctrine/migrations seems coupled to that structure of naming.
