### ISSUE TITLE
Schema builder commands from diff tool

### ISSUE THREAD

**Issue by michaelk83** [laravel-doctrine/migrations#21]
Currently the diff tool only generates a raw SQL migration. It would be useful to have it generate schema builder commands instead, at least as an option. That would be nicer to review and edit, and should also be more portable across different SQL backends (no need to regenerate the migration for each backend).

**Comment by driesvints** [comment]
Since this library is a wrapper for `doctrine/migrations` this should be requested on their own Github repo. There's actually already a length discussion going on here which dates back from 2012: https://github.com/doctrine/migrations/pull/79

**Comment by michaelk83** [comment]
I agree that upstream support would be good, but the builder commands in this library would work with the `Builder` class, which isn't upstream.

With the current state of the upstream code, one can use `Doctrine\DBAL\Schema\Comparator` to get a `Doctrine\DBAL\Schema\SchemaDiff` instance. That's what `Doctrine\DBAL\Schema\Schema::getMigrateToSql()` does internally.

From there it should be possible to implement at least the most common commands for modifying tables. For the less common stuff `getMigrateToSql()` can still be used a fallback.

**Comment by patrickbrouwers** [comment]
Will have to wait for doctrine/migrations#79 . Will see if in the future we can implement the interface ourselves, but highly doubt I will implement that. It's just migrations, it doesn't have to look fancy.
