### ISSUE TITLE
ErrorException: Undefined variable: migration

### ISSUE THREAD

**Issue by ngrevet** [laravel-doctrine/migrations#23]
I've been having an issue lately with the Laravel Doctrine Migration tool where it basically just fails with this error:

```
1) DbTests\Migrations\Version20160309144500Test::testMigration
ErrorException: Undefined variable: migration
/home/travis/build/.../vendor/laravel-doctrine/migrations/src/Console/MigrateCommand.php:64
/home/travis/build/.../vendor/illuminate/container/Container.php:507
/home/travis/build/.../vendor/illuminate/console/Command.php:169
/home/travis/build/.../vendor/symfony/console/Command/Command.php:259
/home/travis/build/.../vendor/illuminate/console/Command.php:155
/home/travis/build/.../vendor/symfony/console/Application.php:844
/home/travis/build/.../vendor/symfony/console/Application.php:192
/home/travis/build/.../vendor/symfony/console/Application.php:123
/home/travis/build/.../vendor/illuminate/console/Application.php:64
/home/travis/build/.../vendor/laravel/lumen-framework/src/Console/Kernel.php:107
/home/travis/build/.../vendor/laravel/lumen-framework/src/Testing/TestCase.php:282
/home/travis/build/.../tests/db/Migrations/TestCase.php:37
```

When you take a look at the file where the issue is happening (`laravel-doctrine/migrations/src/Console/MigrateCommand.php`), it looks like a code defect introduced by this commit: https://github.com/laravel-doctrine/migrations/commit/f9b33815df3753ab3888b8c362f8ae796a46e668
The `$migration` variable used on line 64 might not be available if the try/catch surrounding its assignation fails. I'm pretty sure something is wrong somewhere.

**Comment by patrickbrouwers** [comment]
Seems it only happens when you pass it an invalid version, else the $migration variable is present.

Think it should end the execution after it fails. 
If you could send in a PR to end the execution `MigrationVersionException $e` that would be helpful.

**Comment by ngrevet** [comment]
Not sure how you'd want that done, I could end the execution, but I mean... just putting a `die` there feels wrong.

**Comment by patrickbrouwers** [comment]
Have a look at this suggestion: https://github.com/laravel-doctrine/orm/pull/129

**Comment by driesvints** [comment]
Note that that PR is specifically for the ORM commands. I did went through the migrations commands on this library as well but didn't find places where to add exit codes because the commands here differ significantly from the Doctrine Migrations commands. The logic is quite different in some places.

Perhaps by diving deeper into the logic of this library's commands you could add some exit codes here and there.

However, I do think that the problem here just requires a termination of the migration like you suggest (with an exit code).
