### ISSUE TITLE
Migration stuck on Postgresql database

### ISSUE THREAD

**Issue by chrischnweiss** [laravel-doctrine/migrations#26]
Hi there,

got the following error on migrating two entities two my postrgesql database. These tables are also related with a OneToMany relationship... so what.

Without the relationship the migration runs fine, but after adding the relationship I run in this error:

```
php artisan doctrine:migrations:refresh

  [Doctrine\DBAL\Exception\DriverException]
  An exception occurred while executing 'SET FOREIGN_KEY_CHECKS = 0;':
  SQLSTATE[42704]: Undefined object: 7 ERROR:  unrecognized configuration parameter "foreign_key_checks"

  [Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[42704]: Undefined object: 7 ERROR:  unrecognized configuration parameter "foreign_key_checks"

  [PDOException]
  SQLSTATE[42704]: Undefined object: 7 ERROR:  unrecognized configuration parameter "foreign_key_checks"
```

I know that FOREIGN_KEY_CHECKS not compatible with Postgres, but my doctrine and database configs are also set to postgres.

Any ideas on this?

Thanks and regards,
Christian

**Comment by oddz** [comment]
Sadly the code that does that is hard-coded in the command. You will need to create your own command that uses the postgres implementation of disabling foreign key checks. Long term though I think it would be good for the package to provide different strategies for each platform.

**Comment by patrickbrouwers** [comment]
These are problems related to the parent package "doctrine/migrations". Nothing we can do about that over here.
