### ISSUE TITLE
--dry-run flag ignored when running doctrine:migrations:migrate

### ISSUE THREAD

**Issue by driesvints** [laravel-doctrine/migrations#30]
For some reason, the `--dry-run` flag seems to be ignored when I try to run it with the migrate command. I tried to see where the problem lies but couldn't really find anything. Since this library mostly passes CLI arguments to internal Doctrine classes, not much should be able to go wrong here from this lib's end.

Can anyone perhaps test this out as well so I know this isn't just on my side?

**Comment by dave-redfern** [comment]
@driesvints `--dry-run` needs to be specified as `--dry-run=true` because it is setup as `--dry-run=` so the default is false. If you add =true it will actually do a dry-run.

I know kinda old but answering anyway since I just went through this myself.
