### ISSUE TITLE
Enhancement: per entity manager migration configs

### ISSUE THREAD

**Issue by dave-redfern** [laravel-doctrine/migrations#32]
Ran into this one yesterday: currently the migrations do not allow truly independent migrations for multiple entity managers. You can specify the connection etc. however the generated migrations do not maintain this information or provide a mechanism to only apply specific migrations and very quickly things descend into a mess.

Doing some research and the main Doctrine Migrations allows for a separate configuration to be provided, allowing completely different settings to be used for the migration config e.g: directory, namespace, table name etc.

The exact same thing can be done in this extension with very little extra effort and in a slightly more friendly way. I have implemented this in a branch in a fork of the repo and can make a PR if you want.
Commit: https://github.com/dave-redfern/migrations/commit/6dcc804e6ce24c856cc3c0b6b1eb6d6bb14a93f0

There is a BC break: I changed the config file format very slightly so now, the previous settings are in a connection sub-key. e.g.: migrations.default.name, migrations.default.directory.

The major benefit of all this, is you can have completely separate, isolated migrations including custom folders and namespaces allowing each entity manager to be managed individually. This mostly applies if you want to create an extension and provide entities / repos but it is intended to be run from its own DB but you want to allow the user to still custom and run their own migrations without mucking up their main app.

It's a limited use case I know, but it could maybe be used for different migrations in different environments as well through some creative naming.

Thoughts? Comments?

**Comment by dave-redfern** [comment]
@patrickbrouwers not sure if you saw this or not, so being a little cheeky and pinging you ;)

**Comment by aschwin** [comment]
Hi Dave,

I run into the same issues. We have a legacy database and we need entities from that database. We also have a brand new database and use it as a default.

Updates on the legacy database can not be run, because it is not seen from the migration script. This is a huge flaw indeed. I will look into your PR and see if it is usable for us.

**Comment by dave-redfern** [comment]
@aschwin I'll make the PR will make it easier to see the changes.

**Comment by patrickbrouwers** [comment]
@dave-redfern sorry for the late response I was on holiday. Looks good, thanks for the fallback as well.

**Comment by dave-redfern** [comment]
@patrickbrouwers I made the change requested in PR; no problems - we are all allowed downtime ;)
