### ISSUE TITLE
How to ignore custom tables

### ISSUE THREAD

**Issue by josecelano** [laravel-doctrine/migrations#33]
I have some tables for which there is no doctrine mapping file. When I run:

```
php artisan doctrine:migrations:diff
```

The SQL migration contains a DROP for those tables.

I do not know how to tell doctrine to ignore some tables:

http://doctrine-orm.readthedocs.io/projects/doctrine-migrations/en/latest/reference/generating_migrations.html#ignoring-custom-tables

Is there a way to add a "ignore table list" in the config file?

**Comment by josecelano** [comment]
I saw there is already an option in file:

```
./config/migrations.php
```

Is that the option I am looking for? I will check it.

```
    /*
    |--------------------------------------------------------------------------
    | Migration Repository Table
    |--------------------------------------------------------------------------
    |
    | Tables which are filtered by Regular Expression. You optionally
    | exclude or limit to certain tables. The default will
    | filter all tables.
    |
    */
    'schema'    => [
        'filter' => '/^(?).*$/'
    ]
```

**Comment by patrickbrouwers** [comment]
Yes the `filter` regex option is what you need.

**Comment by FoxxMD** [comment]
@josecelano in case you need an example for the regex here's what my filter looks like for ignoring multiple tables:

```
'schema'    => [
    'filter' => '/^(?!oauth_grants|oauth_sessions|oauth_access_tokens).*$/'
]
```

Use the pipe character to list all the names of tables and fill er up.

**Comment by josecelano** [comment]
Thank you!

**Comment by josecelano** [comment]
hey @FoxxMD I had a problem with that regular expression because it excludes al tables with that prefix not only tables with that full name.

If you want to exclude exactly the tables whose full name is in the regular expresion table list you have to use:

```
    'schema'    => [
        'filter' => '/^(?!\b(oauth_grants|migraoauth_sessions|oauth_access_tokens)\b).*$/'
    ]
```

Notice `\b` option.

**Comment by mmizera** [comment]
This is not a valid solution, migrations.php is configuration for eloquent, not doctrine-migrations. I try to set filter, nothing happend. I even rename/delete migrations.php and doctrine:migrations:diff is still working, thus this config is not loaded/used in any way !
