### ISSUE TITLE
Migration script tries to create migrations table always

### ISSUE THREAD

**Issue by josecelano** [laravel-doctrine/migrations#35]
Hi:

I have renamed migrations table name to avoid conflicts with Laravel/Eloquent migrations table:

```
    /*
    |--------------------------------------------------------------------------
    | Migration Repository Table
    |--------------------------------------------------------------------------
    |
    | This table keeps track of all the migrations that have already run for
    | your application. Using this information, we can determine which of
    | the migrations on disk haven't actually been run in the database.
    |
    */
    'table'     => 'migrations_doctrine',
```

But now, every time I try to execute migration script: `php artisan doctrine:migrations:migrate`
I get this error:

```
 [Doctrine\DBAL\Exception\TableExistsException]
  An exception occurred while executing 'CREATE TABLE migrations_doctrine (version VARCHAR(255) NOT NULL, PRIMARY KEY(version)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB':
  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'migrations_doctrine' already exists
```

I have tried to remove completely the database and then create the schema and run migrations.
The first time I run the migration script it works, but the second time it fails with that error. The `migrations_doctrine` table contains all the versions of the migrations executed the first time.

**Comment by ghost** [comment]
I began to experience this after upgrading to 1.1.0.

**Comment by patrickbrouwers** [comment]
Just tested it with 1.1.0, but I can change the table name to `migrations_doctrine` without any problem, it never tries to recreate it.

Seems it bypasses  this check`if (!$this->connection->getSchemaManager()->tablesExist([$this->migrationsTableName])) {`  in the parent package (doctrine/migrations). 
Maybe you can try to debug it in `Configuration@createMigrationTable`, as I can't reproduce it.

**Comment by ghost** [comment]
In that function $this->migrationsTableName is set to "migrations".
I also found this:
In laravel-doctrine/migrations/src/Configuration/ConfigurationFactory@make, the $name parameter is set to NULL.
As a result this code is executed:
} else {
            $config = new Collection($this->config->get('migrations.default', []));
        }

**Comment by ghost** [comment]
The issue appears to be the **structure** of config/migrations.php
I had:
`
return [
        'table' => 'migrations_doctrine',
        'directory' => database_path('migrations'),
        'namespace' => 'Database\\Migrations',
        'schema' => [
                'filter' => '/^(?).*$/'
        ]
];
`

The vendor version:
`
return [
    'default' => [
        'table'     => 'migrations',
        'directory' => database_path('migrations'),
        'namespace' => 'Database\\Migrations',
        'schema'    => [
            'filter' => '/^(?!password_resets|failed_jobs).*$/'
        ]
    ],
];
`

**Comment by josecelano** [comment]
I have found the problem. My regular expresion to filter tables in `migrations.php` config file was wrong. I was using something like:

```
'schema'    => [
    'filter' => '/^(?!password_resets|migrations).*$/'
]
```

because I wanted to exclude Eloquent migrations table.

That regular expresion excludes also the table `migrations_doctrine`. And that's why doctrine tries to create it, becuase there is a method which returns a list of tables except excludes tables. THe library is using that method to check if 'migrations_doctrine` table exists. Maybe hte table you define for migrations should not be excluded even if that table matches the filter to exclude tables from doctrine.

This is the rigth version for the regular expresion if you want each table to be the full name of the table not only a table with that prefix.:

```
'schema'    => [
    'filter' => '/^(?!\b(password_resets|migrations)\b).*$/'
]
```

I had opened another issue related to this:

https://github.com/laravel-doctrine/migrations/issues/33

**Comment by jttfbd** [comment]
[Illuminate\Database\QueryException] SQLSTATE[42501]: Base table or view already exists: 1050 Table 'password_resets' already exists (SQL: create table 'password_resets' ("email' varchar(255) not null, 'token' varchar(255) not null, 'created_at' timestamp null) defau It character set utfSmb4 collate utfSmb4_unicode_ci) 

[PDOException] SQLSTATE[42501]: Base table or view already exists: 1050 Table 'password_resets' already exists 


how i can solution this problem please anyone help me
