### ISSUE TITLE
Testing UseDatabaseMigrations UUID error

### ISSUE THREAD

**Issue by XanManZA** [laravel-doctrine/migrations#36]
So not sure if this is the right place.
I think I found an error when trying to use the DatabaseMigrations trait on my Test classes. I have tried multiple avenues for the past few days, but keep getting the same error:

> Doctrine\DBAL\DBALException: Unknown column type "uuid" requested.

I'm not sure if this trait uses your existing migrations? But I do have statements like
`$table->uuid('id');`
in my migrations that those tests might use.

**Comment by patrickbrouwers** [comment]
We don't have any `$table->uuid('id');`, are you sure you are using Laravel-Doctrine and not just Eloquent?

**Comment by XanManZA** [comment]
Double-checked! Yes, using Eloquent, my mistake. Will close.
Thank you!
