### ISSUE TITLE
Update version constraints for laravel-doctrine/orm 

### ISSUE THREAD

**Issue by LavaToaster** [laravel-doctrine/migrations#42]
Currently working around this by aliasing the new release in my composer.json file:

```
        "laravel-doctrine/orm": "1.3.0 as 1.2.10",
```

**Comment by patrickbrouwers** [comment]
Should be fixed.

**Comment by LavaToaster** [comment]
❤️ 

(Already said this on slack, but here's some more public appreciation)

**Comment by patrickbrouwers** [comment]
Haha thanks @Lavoaster, much appreciated :)
