### ISSUE TITLE
add support for laravel 5.5

### ISSUE THREAD

**Issue by meltzow** [laravel-doctrine/migrations#53]
after I upgrade to laravel 5.5. an laravel-doctrine/orm 1.3.x-dev

I got the following message: 

[ReflectionException]                                                        
Method LaravelDoctrine\Migrations\Console\MigrateCommand::handle() does not  exist 

https://laravel.com/docs/5.5/upgrade says: 

The fire Method
Any fire methods present on your Artisan commands should be renamed to handle.

**Comment by meltzow** [comment]
I see you got a PR for it: https://github.com/laravel-doctrine/migrations/pull/52

**Comment by patrickbrouwers** [comment]
Btw use 1.4.* for ORM. 1.3 doesn't have 5.5 support
