### ISSUE TITLE
Unexpected error in console commands in Lumen 5.5

### ISSUE THREAD

**Issue by retnek** [laravel-doctrine/migrations#54]
Hello,

After I upgraded my Lumen from 5.4.36 to 5.5 the doctrine migration commands aren't working properly anymore, I've got an exception:

`ReflectionException: Method LaravelDoctrine\Migrations\Console\GenerateCommand::handle() does not exist in ...`

If I run `doctrine:migration:diff` then I've got a similar exception:

`ReflectionException: Method LaravelDoctrine\Migrations\Console\DiffCommand::handle() does not exist in...`

so in my opinion the migration commands are not working at all in Lumen 5.5.

**Comment by patrickbrouwers** [comment]
Can you check if you are running on the latest version of LD-migrations? it should be 1.1.6

**Comment by retnek** [comment]
I didn't use the latest package of LD-migrations (1.0.5) so after I upated the package to 1.1.6 the issue has been solved. Sorry about that.
