### ISSUE TITLE
Unable to run migrations 

### ISSUE THREAD

**Issue by jesseyofferenvan** [laravel-doctrine/migrations#59]
Recently installed laravel-doctrine in my laravel 5.5 project and started making migrations using doctrine. Now when I try to run: `php artisan doctrine:migrations:migrate`

It returns the following error: 

In Version20180122094236.php line 20:

  Call to undefined method Doctrine\DBAL\Schema\Column::index()

This is the migration file it's complaining about:
```

<?php

namespace Database\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema as Schema;
use LaravelDoctrine\Migrations\Schema\Table;
use LaravelDoctrine\Migrations\Schema\Builder;

class Version20180122094136 extends AbstractMigration
{
    protected $tableName = "users";

    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        (new Builder($schema))->create($this->tableName, function (Table $table) {
            $table->increments('id');
            $table->string('name');
            $table->string('email');
            $table->string('password');
            $table->rememberToken();
            $table->timestamps();
        });
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        (new Builder($schema))->drop($this->tableName);
    }
}
```

my composer.json looks as follow: 

```
 "require": {
        "php": ">=7.0.0",
        "doctrine/dbal": "^2.6",
        "fideloper/proxy": "~3.3",
        "laravel-doctrine/migrations": "^1.1",
        "laravel-doctrine/orm": "1.4.*",
        "laravel/framework": "5.5.*",
        "laravel/tinker": "~1.0"
    }
```

Any tips of what may cause this error?

**Comment by patrickbrouwers** [comment]
Hey @jesseyofferenvan 

Are you sure you are showing the right migration file? Your error is about `Version20180122094236` , the migration is called `Version20180122094136`.

**Comment by rela589n** [comment]
What am i doing wrong? Why does doctrine trying to insert new entry into standard `migrations` table?

![image](https://user-images.githubusercontent.com/41589422/99877000-a209b000-2c03-11eb-967c-32d86d97e741.png)

**Comment by eigan** [comment]
@rela589n Please open a new issue. Include list of your current installed dependencies (`composer show | grep doctrine`), and output of `describe migrations` from your db table.

**Comment by rela589n** [comment]
I suppose problem is related to collision with native laravel migrations table (it has a different structure)
