### ISSUE TITLE
[Bug?] --query-time option for MigrateCommand ignores blank value

### ISSUE THREAD

**Issue by garret-gunter** [laravel-doctrine/migrations#61]
## Description

When running `doctrine:migrations:migrate` the `--query-time` option won't be counted unless you pass something to it.  The command does not care what you put after, it will work with `doctrine:migrations:migrate --query-time='hello'`.

Code where the option is checked.
https://github.com/laravel-doctrine/migrations/blob/f1292c3dcb894bf5d310775e4bb1d9bd9e74d658/src/Console/MigrateCommand.php#L72-L76

Current signature:
https://github.com/laravel-doctrine/migrations/blob/f1292c3dcb894bf5d310775e4bb1d9bd9e74d658/src/Console/MigrateCommand.php#L18-L28

## Expected Behavior

The `--query-time` option should act like a standard boolean option.  If I call the command with `php artisan doctrine:migrations:migrate --query-time`, it should report query times.

## Actual Behavior

`--query-time` is ignored if there is no value passed to it.  But any value passed to is treated as true.

## Possible Fix

There are two options I've come up with:

**1)  Change the option signature.**

Change ` {--query-time= : Time all the queries individually. }` to ` {--query-time : Time all the queries individually. }`.  This will break current behavior, but treats the option like a switch both internally and externally.

**2)  Add default and change how the option is checked.**  

Change ` {--query-time= : Time all the queries individually. }` to `{--query-time=false : Time all the queries individually. }`.

Change the logic to check for 'false' since `--query-time` will pass `null` as the value, while not using the option will return the string 'false':
```php

$shouldTimeQuery = $this->option('query-time') !== 'false';

```
```php
$migrator->migrate(
      $migration,
      $this->option('dry-run') ? true : false,
      $shouldTimeQuery
);
```  
  
  
I personally prefer the first option.  While it does change current behavior, it's more clear on how to use the option.  The second option feels really dirty, but it works and preserves current behavior.  

## Steps to Reproduce  

1.  Create a migration.  
2.  Run `php artisan doctrine:migrations:migrate --dry-run --query-time`  
3.  The migrations will not be timed.  
4.  Run `php artisan doctrine:migrations:migrate --dry-run --query-time='random string'`  
5.  The migrations will be timed.

**Comment by garret-gunter** [comment]
I can make a pull request.

**Comment by patrickbrouwers** [comment]
PR would be great, thanks

**Comment by SPie** [comment]
I can open a PR if you are ok with it, @garret-gunter .
I would use your first option, because I think this is the right way of using this option, even it could break some implementations. Maybe this needs to be merged to the next minor version then.
