### ISSUE TITLE
[Bug] Add all versions do not work

### ISSUE THREAD

**Issue by lmillucci** [laravel-doctrine/migrations#65]
# Package version, Laravel version
Laravel Framework 5.5.33
laravel-doctrine/migrations": 1.1.7
laravel-doctrine/orm": 1.4.3

# Expected behavior
`php artisan doctrine:migrations:version --all --add`
should add all versions

# Actual behavior
```
php artisan doctrine:migrations:version --all --add

Not enough arguments (missing: "version").
```  
                                              
I think that a possible solution is to mark as optional `version` argument in the `VersionCommand`

**Comment by patrickbrouwers** [comment]
Sorry for the late reply, can you make a PR for your solution, thanks.
