### ISSUE TITLE
Undefined method Kernel::setArtisan() in DatabaseMigrations trait

### ISSUE THREAD

**Issue by SPie** [laravel-doctrine/migrations#68]
I'm using the DatabaseMigrations trait for my tests  with Lumen 5.6 and I'm getting this error:
`Call to undefined method App\Console\Kernel::setArtisan()`

Is it possible that the line 
`$this->app[Kernel::class]->setArtisan(null);`
just worked for a previous Laravel version, or did I miss to bind a special Kernel?

**Comment by eigan** [comment]
Are you extending `Illuminate\Foundation\Console\Kernel`?
https://github.com/laravel/framework/blob/5.6/src/Illuminate/Foundation/Console/Kernel.php#L330

**Comment by SPie** [comment]
Sorry, I mixed it up a little.
I'm using Lumen 5.6 and the Lumen Kernel doesn't provide the method `setArtisan()`.

**Comment by patrickbrouwers** [comment]
Happy to accept a PR with better Lumen support.

**Comment by SPie** [comment]
I'd like to do that, but the problem is, I don't know exactly what this line is for.
Otherwise, I would just remove it, because it doesn't make sense to me.

**Comment by patrickbrouwers** [comment]
I think it's copied from Laravel, you could have a look over there how they solved the problem with Lumen? I think it needs to stay for Laravel.

**Comment by eigan** [comment]
https://github.com/laravel/lumen-framework/blob/b31cac1714122469e01b152dd963d11ac6293298/src/Testing/DatabaseMigrations.php

Should be ok to remove it for Lumen.
