### ISSUE TITLE
[Bug] VersionCommand --no-interaction should add migrations without asking confirmation

### ISSUE THREAD

**Issue by lmillucci** [laravel-doctrine/migrations#70]
# Package version, Laravel version
Laravel Framework 5.5.33
laravel-doctrine/migrations": 1.1.9
laravel-doctrine/orm": 1.4.3

# Expected behavior
`php artisan doctrine:migrations:version --all --add --no-interaction`
should add all versions without asking for confirmation

# Actual behavior

```
php artisan doctrine:migrations:version --all --add --no-interaction
Migration cancelled!
```

I'm going to submit a PR with a viable solution

**Comment by patrickbrouwers** [comment]
Merged the PR
