### ISSUE TITLE
Add support for Doctrine Migrations 2.0

### ISSUE THREAD

**Issue by jwage** [laravel-doctrine/migrations#73]
I have been working on Doctrine Migrations 2.0 in https://github.com/doctrine/migrations master.

Opening an issue here to discuss and track progress for upgrading this library to 2.0.

**Comment by patrickbrouwers** [comment]
Thanks for the heads-up @jwage !

**Comment by AnatolyRugalev** [comment]
[Upgrade instructions](https://github.com/doctrine/migrations/blob/master/UPGRADE.md) looks pretty simple.

Shall we support both versions after stable release of 2.0?

**Comment by vv12131415** [comment]
@jwage can you help me with reviewing PR when I'll make one?

**Comment by jwage** [comment]
Yes

**Comment by blacktemplar** [comment]
Any progress?

**Comment by chewbakartik** [comment]
This should be closed, 2.0 is supported in the current latest release `2.1.0`
