### ISSUE TITLE
Call to undefined function LaravelDoctrine\Migrations\str_contains()

### ISSUE THREAD

**Issue by dextercampos** [laravel-doctrine/migrations#89]
Since Laravel 6.0, `str_` and `array_` helpers have been moved to a new package. Instead of requiring this new `laravel/helpers` package, it's better if we use what's already under  #`Illuminate\Support`.

**Comment by dextercampos** [comment]
Created a PR for this #88 ;)

**Comment by eigan** [comment]
Merged :)

**Comment by eigan** [comment]
Released in `1.3.1`.
