### ISSUE TITLE
migration on different env or connection

### ISSUE THREAD

**Issue by mitjarobic** [laravel-doctrine/migrations#9]
How can i do that?

This always returns Doctrine Connection named "pgsql" does not exist.

```
php artisan --connection=pgsql doctrine:migration:migrate
```

This always loads the environment defined in .env file

```
php artisan --env=testing doctrine:migration:migrate
```

**Comment by patrickbrouwers** [comment]
Is your connection actually named pqsql? (The array key)

**Comment by mitjarobic** [comment]
pgsql, yes
