### ISSUE TITLE
Dependency problem with doctrine/migrations 1.4.0 in Laravel 7.4.0

### ISSUE THREAD

**Issue by lsrzj** [laravel-doctrine/migrations#93]
I tried to install laravel-doctrine/migrations in Laravel 7.4.0 and I'm getting dependency problems with it check composer output.

`
Problem 1
    - Conclusion: don't install laravel-doctrine/migrations 1.4.0
    - Conclusion: remove symfony/console v5.0.7
    - Installation request for laravel-doctrine/migrations ^1.4 -> satisfiable by laravel-doctrine/migrations[1.4.0, 1.4.x-dev].
    - Conclusion: don't install symfony/console v5.0.7
    - laravel-doctrine/migrations 1.4.x-dev requires doctrine/migrations ~1.8 -> satisfiable by doctrine/migrations[1.8.x-dev, v1.8.0, v1.8.1].
    - doctrine/migrations 1.8.x-dev requires symfony/console ~3.3|^4.0 -> satisfiable by symfony/console[3.3.x-dev, 3.4.x-dev, 4.0.x-dev, 4.1.x-dev, 4.2.x-dev, 4.3.x-dev, 4.4.x-dev, v3.3.0, v3.3.0-BETA1, v3.3.0-RC1, v3.3.1, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.14, v3.3.15, v3.3.16, v3.3.17, v3.3.18, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0, v3.4.0-BETA1, v3.4.0-BETA2, v3.4.0-BETA3, v3.4.0-BETA4, v3.4.0-RC1, v3.4.0-RC2, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.16, v3.4.17, v3.4.18, v3.4.19, v3.4.2, v3.4.20, v3.4.21, v3.4.22, v3.4.23, v3.4.24, v3.4.25, v3.4.26, v3.4.27, v3.4.28, v3.4.29, v3.4.3, v3.4.30, v3.4.31, v3.4.32, v3.4.33, v3.4.34, v3.4.35, v3.4.36, v3.4.37, v3.4.38, v3.4.39, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9, v4.0.0, v4.0.0-BETA1, v4.0.0-BETA2, v4.0.0-BETA3, v4.0.0-BETA4, v4.0.0-RC1, v4.0.0-RC2, v4.0.1, v4.0.10, v4.0.11, v4.0.12, v4.0.13, v4.0.14, v4.0.15, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8, v4.0.9, v4.1.0, v4.1.0-BETA1, v4.1.0-BETA2, v4.1.0-BETA3, v4.1.1, v4.1.10, v4.1.11, v4.1.12, v4.1.2, v4.1.3, v4.1.4, v4.1.5, v4.1.6, v4.1.7, v4.1.8, v4.1.9, v4.2.0, v4.2.0-BETA1, v4.2.0-BETA2, v4.2.0-RC1, v4.2.1, v4.2.10, v4.2.11, v4.2.12, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9, v4.3.0, v4.3.0-BETA1, v4.3.0-BETA2, v4.3.0-RC1, v4.3.1, v4.3.10, v4.3.11, v4.3.2, v4.3.3, v4.3.4, v4.3.5, v4.3.6, v4.3.7, v4.3.8, v4.3.9, v4.4.0, v4.4.0-BETA1, v4.4.0-BETA2, v4.4.0-RC1, v4.4.1, v4.4.2, v4.4.3, v4.4.4, v4.4.5, v4.4.6, v4.4.7].
    - doctrine/migrations v1.8.1 requires symfony/console ~3.3|^4.0 -> satisfiable by symfony/console[3.3.x-dev, 3.4.x-dev, 4.0.x-dev, 4.1.x-dev, 4.2.x-dev, 4.3.x-dev, 4.4.x-dev, v3.3.0, v3.3.0-BETA1, v3.3.0-RC1, v3.3.1, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.14, v3.3.15, v3.3.16, v3.3.17, v3.3.18, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0, v3.4.0-BETA1, v3.4.0-BETA2, v3.4.0-BETA3, v3.4.0-BETA4, v3.4.0-RC1, v3.4.0-RC2, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.16, v3.4.17, v3.4.18, v3.4.19, v3.4.2, v3.4.20, v3.4.21, v3.4.22, v3.4.23, v3.4.24, v3.4.25, v3.4.26, v3.4.27, v3.4.28, v3.4.29, v3.4.3, v3.4.30, v3.4.31, v3.4.32, v3.4.33, v3.4.34, v3.4.35, v3.4.36, v3.4.37, v3.4.38, v3.4.39, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9, v4.0.0, v4.0.0-BETA1, v4.0.0-BETA2, v4.0.0-BETA3, v4.0.0-BETA4, v4.0.0-RC1, v4.0.0-RC2, v4.0.1, v4.0.10, v4.0.11, v4.0.12, v4.0.13, v4.0.14, v4.0.15, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8, v4.0.9, v4.1.0, v4.1.0-BETA1, v4.1.0-BETA2, v4.1.0-BETA3, v4.1.1, v4.1.10, v4.1.11, v4.1.12, v4.1.2, v4.1.3, v4.1.4, v4.1.5, v4.1.6, v4.1.7, v4.1.8, v4.1.9, v4.2.0, v4.2.0-BETA1, v4.2.0-BETA2, v4.2.0-RC1, v4.2.1, v4.2.10, v4.2.11, v4.2.12, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9, v4.3.0, v4.3.0-BETA1, v4.3.0-BETA2, v4.3.0-RC1, v4.3.1, v4.3.10, v4.3.11, v4.3.2, v4.3.3, v4.3.4, v4.3.5, v4.3.6, v4.3.7, v4.3.8, v4.3.9, v4.4.0, v4.4.0-BETA1, v4.4.0-BETA2, v4.4.0-RC1, v4.4.1, v4.4.2, v4.4.3, v4.4.4, v4.4.5, v4.4.6, v4.4.7].
    - doctrine/migrations v1.8.0 requires symfony/console ^3.4||^4.0 -> satisfiable by symfony/console[3.4.x-dev, 4.0.x-dev, 4.1.x-dev, 4.2.x-dev, 4.3.x-dev, 4.4.x-dev, v3.4.0, v3.4.0-BETA1, v3.4.0-BETA2, v3.4.0-BETA3, v3.4.0-BETA4, v3.4.0-RC1, v3.4.0-RC2, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.16, v3.4.17, v3.4.18, v3.4.19, v3.4.2, v3.4.20, v3.4.21, v3.4.22, v3.4.23, v3.4.24, v3.4.25, v3.4.26, v3.4.27, v3.4.28, v3.4.29, v3.4.3, v3.4.30, v3.4.31, v3.4.32, v3.4.33, v3.4.34, v3.4.35, v3.4.36, v3.4.37, v3.4.38, v3.4.39, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9, v4.0.0, v4.0.0-BETA1, v4.0.0-BETA2, v4.0.0-BETA3, v4.0.0-BETA4, v4.0.0-RC1, v4.0.0-RC2, v4.0.1, v4.0.10, v4.0.11, v4.0.12, v4.0.13, v4.0.14, v4.0.15, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8, v4.0.9, v4.1.0, v4.1.0-BETA1, v4.1.0-BETA2, v4.1.0-BETA3, v4.1.1, v4.1.10, v4.1.11, v4.1.12, v4.1.2, v4.1.3, v4.1.4, v4.1.5, v4.1.6, v4.1.7, v4.1.8, v4.1.9, v4.2.0, v4.2.0-BETA1, v4.2.0-BETA2, v4.2.0-RC1, v4.2.1, v4.2.10, v4.2.11, v4.2.12, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9, v4.3.0, v4.3.0-BETA1, v4.3.0-BETA2, v4.3.0-RC1, v4.3.1, v4.3.10, v4.3.11, v4.3.2, v4.3.3, v4.3.4, v4.3.5, v4.3.6, v4.3.7, v4.3.8, v4.3.9, v4.4.0, v4.4.0-BETA1, v4.4.0-BETA2, v4.4.0-RC1, v4.4.1, v4.4.2, v4.4.3, v4.4.4, v4.4.5, v4.4.6, v4.4.7].
    - Can only install one of: symfony/console[3.3.x-dev, v5.0.7].
    - Can only install one of: symfony/console[3.4.x-dev, v5.0.7].
    - Can only install one of: symfony/console[4.0.x-dev, v5.0.7].
    - Can only install one of: symfony/console[4.1.x-dev, v5.0.7].
    - Can only install one of: symfony/console[4.2.x-dev, v5.0.7].
    - Can only install one of: symfony/console[4.3.x-dev, v5.0.7].
    - Can only install one of: symfony/console[4.4.x-dev, v5.0.7].
    - Can only install one of: symfony/console[v3.3.0, v5.0.7].
    - Can only install one of: symfony/console[v3.3.0-BETA1, v5.0.7].
    - Can only install one of: symfony/console[v3.3.0-RC1, v5.0.7].
    - Can only install one of: symfony/console[v3.3.1, v5.0.7].
    - Can only install one of: symfony/console[v3.3.10, v5.0.7].
    - Can only install one of: symfony/console[v3.3.11, v5.0.7].
    - Can only install one of: symfony/console[v3.3.12, v5.0.7].
    - Can only install one of: symfony/console[v3.3.13, v5.0.7].
    - Can only install one of: symfony/console[v3.3.14, v5.0.7].
    - Can only install one of: symfony/console[v3.3.15, v5.0.7].
    - Can only install one of: symfony/console[v3.3.16, v5.0.7].
    - Can only install one of: symfony/console[v3.3.17, v5.0.7].
    - Can only install one of: symfony/console[v3.3.18, v5.0.7].
    - Can only install one of: symfony/console[v3.3.2, v5.0.7].
    - Can only install one of: symfony/console[v3.3.3, v5.0.7].
    - Can only install one of: symfony/console[v3.3.4, v5.0.7].
    - Can only install one of: symfony/console[v3.3.5, v5.0.7].
    - Can only install one of: symfony/console[v3.3.6, v5.0.7].
    - Can only install one of: symfony/console[v3.3.7, v5.0.7].
    - Can only install one of: symfony/console[v3.3.8, v5.0.7].
    - Can only install one of: symfony/console[v3.3.9, v5.0.7].
    - Can only install one of: symfony/console[v3.4.0, v5.0.7].
    - Can only install one of: symfony/console[v3.4.0-BETA1, v5.0.7].
    - Can only install one of: symfony/console[v3.4.0-BETA2, v5.0.7].
    - Can only install one of: symfony/console[v3.4.0-BETA3, v5.0.7].
    - Can only install one of: symfony/console[v3.4.0-BETA4, v5.0.7].
    - Can only install one of: symfony/console[v3.4.0-RC1, v5.0.7].
    - Can only install one of: symfony/console[v3.4.0-RC2, v5.0.7].
    - Can only install one of: symfony/console[v3.4.1, v5.0.7].
    - Can only install one of: symfony/console[v3.4.10, v5.0.7].
    - Can only install one of: symfony/console[v3.4.11, v5.0.7].
    - Can only install one of: symfony/console[v3.4.12, v5.0.7].
    - Can only install one of: symfony/console[v3.4.13, v5.0.7].
    - Can only install one of: symfony/console[v3.4.14, v5.0.7].
    - Can only install one of: symfony/console[v3.4.15, v5.0.7].
    - Can only install one of: symfony/console[v3.4.16, v5.0.7].
    - Can only install one of: symfony/console[v3.4.17, v5.0.7].
    - Can only install one of: symfony/console[v3.4.18, v5.0.7].
    - Can only install one of: symfony/console[v3.4.19, v5.0.7].
    - Can only install one of: symfony/console[v3.4.2, v5.0.7].
    - Can only install one of: symfony/console[v3.4.20, v5.0.7].
    - Can only install one of: symfony/console[v3.4.21, v5.0.7].
    - Can only install one of: symfony/console[v3.4.22, v5.0.7].
    - Can only install one of: symfony/console[v3.4.23, v5.0.7].
    - Can only install one of: symfony/console[v3.4.24, v5.0.7].
    - Can only install one of: symfony/console[v3.4.25, v5.0.7].
    - Can only install one of: symfony/console[v3.4.26, v5.0.7].
    - Can only install one of: symfony/console[v3.4.27, v5.0.7].
    - Can only install one of: symfony/console[v3.4.28, v5.0.7].
    - Can only install one of: symfony/console[v3.4.29, v5.0.7].
    - Can only install one of: symfony/console[v3.4.3, v5.0.7].
    - Can only install one of: symfony/console[v3.4.30, v5.0.7].
    - Can only install one of: symfony/console[v3.4.31, v5.0.7].
    - Can only install one of: symfony/console[v3.4.32, v5.0.7].
    - Can only install one of: symfony/console[v3.4.33, v5.0.7].
    - Can only install one of: symfony/console[v3.4.34, v5.0.7].
    - Can only install one of: symfony/console[v3.4.35, v5.0.7].
    - Can only install one of: symfony/console[v3.4.36, v5.0.7].
    - Can only install one of: symfony/console[v3.4.37, v5.0.7].
    - Can only install one of: symfony/console[v3.4.38, v5.0.7].
    - Can only install one of: symfony/console[v3.4.39, v5.0.7].
    - Can only install one of: symfony/console[v3.4.4, v5.0.7].
    - Can only install one of: symfony/console[v3.4.5, v5.0.7].
    - Can only install one of: symfony/console[v3.4.6, v5.0.7].
    - Can only install one of: symfony/console[v3.4.7, v5.0.7].
    - Can only install one of: symfony/console[v3.4.8, v5.0.7].
    - Can only install one of: symfony/console[v3.4.9, v5.0.7].
    - Can only install one of: symfony/console[v4.0.0, v5.0.7].
    - Can only install one of: symfony/console[v4.0.0-BETA1, v5.0.7].
    - Can only install one of: symfony/console[v4.0.0-BETA2, v5.0.7].
    - Can only install one of: symfony/console[v4.0.0-BETA3, v5.0.7].
    - Can only install one of: symfony/console[v4.0.0-BETA4, v5.0.7].
    - Can only install one of: symfony/console[v4.0.0-RC1, v5.0.7].
    - Can only install one of: symfony/console[v4.0.0-RC2, v5.0.7].
    - Can only install one of: symfony/console[v4.0.1, v5.0.7].
    - Can only install one of: symfony/console[v4.0.10, v5.0.7].
    - Can only install one of: symfony/console[v4.0.11, v5.0.7].
    - Can only install one of: symfony/console[v4.0.12, v5.0.7].
    - Can only install one of: symfony/console[v4.0.13, v5.0.7].
    - Can only install one of: symfony/console[v4.0.14, v5.0.7].
    - Can only install one of: symfony/console[v4.0.15, v5.0.7].
    - Can only install one of: symfony/console[v4.0.2, v5.0.7].
    - Can only install one of: symfony/console[v4.0.3, v5.0.7].
    - Can only install one of: symfony/console[v4.0.4, v5.0.7].
    - Can only install one of: symfony/console[v4.0.5, v5.0.7].
    - Can only install one of: symfony/console[v4.0.6, v5.0.7].
    - Can only install one of: symfony/console[v4.0.7, v5.0.7].
    - Can only install one of: symfony/console[v4.0.8, v5.0.7].
    - Can only install one of: symfony/console[v4.0.9, v5.0.7].
    - Can only install one of: symfony/console[v4.1.0, v5.0.7].
    - Can only install one of: symfony/console[v4.1.0-BETA1, v5.0.7].
    - Can only install one of: symfony/console[v4.1.0-BETA2, v5.0.7].
    - Can only install one of: symfony/console[v4.1.0-BETA3, v5.0.7].
    - Can only install one of: symfony/console[v4.1.1, v5.0.7].
    - Can only install one of: symfony/console[v4.1.10, v5.0.7].
    - Can only install one of: symfony/console[v4.1.11, v5.0.7].
    - Can only install one of: symfony/console[v4.1.12, v5.0.7].
    - Can only install one of: symfony/console[v4.1.2, v5.0.7].
    - Can only install one of: symfony/console[v4.1.3, v5.0.7].
    - Can only install one of: symfony/console[v4.1.4, v5.0.7].
    - Can only install one of: symfony/console[v4.1.5, v5.0.7].
    - Can only install one of: symfony/console[v4.1.6, v5.0.7].
    - Can only install one of: symfony/console[v4.1.7, v5.0.7].
    - Can only install one of: symfony/console[v4.1.8, v5.0.7].
    - Can only install one of: symfony/console[v4.1.9, v5.0.7].
    - Can only install one of: symfony/console[v4.2.0, v5.0.7].
    - Can only install one of: symfony/console[v4.2.0-BETA1, v5.0.7].
    - Can only install one of: symfony/console[v4.2.0-BETA2, v5.0.7].
    - Can only install one of: symfony/console[v4.2.0-RC1, v5.0.7].
    - Can only install one of: symfony/console[v4.2.1, v5.0.7].
    - Can only install one of: symfony/console[v4.2.10, v5.0.7].
    - Can only install one of: symfony/console[v4.2.11, v5.0.7].
    - Can only install one of: symfony/console[v4.2.12, v5.0.7].
    - Can only install one of: symfony/console[v4.2.2, v5.0.7].
    - Can only install one of: symfony/console[v4.2.3, v5.0.7].
    - Can only install one of: symfony/console[v4.2.4, v5.0.7].
    - Can only install one of: symfony/console[v4.2.5, v5.0.7].
    - Can only install one of: symfony/console[v4.2.6, v5.0.7].
    - Can only install one of: symfony/console[v4.2.7, v5.0.7].
    - Can only install one of: symfony/console[v4.2.8, v5.0.7].
    - Can only install one of: symfony/console[v4.2.9, v5.0.7].
    - Can only install one of: symfony/console[v4.3.0, v5.0.7].
    - Can only install one of: symfony/console[v4.3.0-BETA1, v5.0.7].
    - Can only install one of: symfony/console[v4.3.0-BETA2, v5.0.7].
    - Can only install one of: symfony/console[v4.3.0-RC1, v5.0.7].
    - Can only install one of: symfony/console[v4.3.1, v5.0.7].
    - Can only install one of: symfony/console[v4.3.10, v5.0.7].
    - Can only install one of: symfony/console[v4.3.11, v5.0.7].
    - Can only install one of: symfony/console[v4.3.2, v5.0.7].
    - Can only install one of: symfony/console[v4.3.3, v5.0.7].
    - Can only install one of: symfony/console[v4.3.4, v5.0.7].
    - Can only install one of: symfony/console[v4.3.5, v5.0.7].
    - Can only install one of: symfony/console[v4.3.6, v5.0.7].
    - Can only install one of: symfony/console[v4.3.7, v5.0.7].
    - Can only install one of: symfony/console[v4.3.8, v5.0.7].
    - Can only install one of: symfony/console[v4.3.9, v5.0.7].
    - Can only install one of: symfony/console[v4.4.0, v5.0.7].
    - Can only install one of: symfony/console[v4.4.0-BETA1, v5.0.7].
    - Can only install one of: symfony/console[v4.4.0-BETA2, v5.0.7].
    - Can only install one of: symfony/console[v4.4.0-RC1, v5.0.7].
    - Can only install one of: symfony/console[v4.4.1, v5.0.7].
    - Can only install one of: symfony/console[v4.4.2, v5.0.7].
    - Can only install one of: symfony/console[v4.4.3, v5.0.7].
    - Can only install one of: symfony/console[v4.4.4, v5.0.7].
    - Can only install one of: symfony/console[v4.4.5, v5.0.7].
    - Can only install one of: symfony/console[v4.4.6, v5.0.7].
    - Can only install one of: symfony/console[v4.4.7, v5.0.7].
    - Installation request for symfony/console (locked at v5.0.7) -> satisfiable by symfony/console[v5.0.7].
`

**Comment by dpslwk** [comment]
Unfortunately `laravel-doctrine/migrations` 1.4 should not have been released  
there is no current working support for L7 in migrations, this is being worked on and will be release as 2.0, but it's taking some effort as the underlying  `doctrine/migrations` needs to be updated to at least 2.2.x. 
the new release will be under 2.0 not 1.4 as the move to doctrine/migrations 2.2.x may well introduce BC’s

this has also been mentioned here laravel-doctrine/orm/issues/436
and is being discussed in slack

**Comment by eigan** [comment]
laravel-doctrine/migrations 2.0 is now released with support for Laravel 7, thanks to @chewbakartik! 

Note that there is some breaking changes because of the upgrade to doctrine/migrations 2.0. See the release notes here: https://github.com/laravel-doctrine/migrations/releases/tag/2.0.0

**Comment by lsrzj** [comment]
Well, I tried to install with 2.0 and I had success, so I'll close the issue.
